trigger:
  branches:
    include:
      - main

pool: self-hosted-pool

variables:
  workingDir: 'modules'
  terraformPluginCache: '$(System.DefaultWorkingDirectory)\terraform_plugins'

stages:
- stage: initPlanApply
  displayName: Terraform Init/Plan/Apply
  jobs:
  - job: terraform
    displayName: Terraform Job
    steps:

    # 0️⃣ Set Terraform plugin cache environment variable
    - powershell: |
        Write-Host "##vso[task.setvariable variable=TF_PLUGIN_CACHE_DIR]$(terraformPluginCache)"
      displayName: 'Set TF_PLUGIN_CACHE_DIR'

    # 1️⃣ Create plugin cache folder
    - powershell: |
        if (!(Test-Path -Path "$(terraformPluginCache)")) {
            New-Item -ItemType Directory -Path "$(terraformPluginCache)" | Out-Null
        }
        Write-Host "Terraform plugin cache: $(terraformPluginCache)"
      displayName: 'Create Terraform plugin cache folder'

    # 2️⃣ Terraform Init
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDir)'
        backendServiceArm: 'pr-connection'
        backendAzureRmResourceGroupName: 'pr-store-group'
        backendAzureRmStorageAccountName: 'prstorageaccount01'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'pr.statefile'

    # 3️⃣ Terraform Plan
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDir)'
        environmentServiceNameAzureRM: 'pr-connection'

    # 4️⃣ Terraform Apply
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(workingDir)'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'pr-connection'
